### ISSUE TITLE
Installation not working from gitt.io

### ISSUE THREAD

**Issue by HazemKhaled** [appcelerator-archive/ti.paint#19]
ti.pain on gitt.io linked with another repo

cc @FokkeZB

**Comment by FokkeZB** [comment]
@HazemKhaled somehow gitTio doesn't pick up https://github.com/appcelerator-archive/ti.paint and so it links the best alternative it can find. Which is strange, because gitTio simply does:

https://github.com/appcelerator-archive/ti.paint/search?q=moduleid+AND+guid+AND+minsdk+AND+platform+filename%3Amanifest+in%3Afile

Which works fine...

Mmm 😭

**Comment by hansemannn** [comment]
I don't see this as a code-level issue, so please check with @FokkeZB if it might be something with gittio. If the problem could be related to this repo, let me know on Slack or JIRA, thanks!
